# This is a basic workflow

name: Make .mo file

on:
  workflow_dispatch:

jobs:
  upload_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Git
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com
          
      - name: make local mo file
        run: |
          sudo apt-get update
          sudo apt-get install gettext
          ROOT_PATH=${{ github.workspace }}
          cd ${ROOT_PATH}/
          echo "${ROOT_PATH}"

          echo "make po begin"
          . ./i18n.h
          #for L in `echo "en_US ko_KR ja_JP zh_CN ru_RU fr_FR de_DE es_ES it_IT pt_BR ar_EG hi_IN hu_HU id_ID tr_TR am_ET th_TH"`; do
          for L in `echo "am_ET th_TH"`; do
              [ ! -d "lang/${L}/LC_MESSAGES" ] && mkdir -p lang/${L}/LC_MESSAGES    
              lcode=$(echo ${L} | cut -c 4-)
              llang=$(echo ${L} | cut -c 1-2)
              cat Charset-header.h > lang/${L}/LC_MESSAGES/tcrp.po
              sed -i "s#l_lang#${llang}#" lang/${L}/LC_MESSAGES/tcrp.po
              sed -i "s#locale#${L}#" lang/${L}/LC_MESSAGES/tcrp.po                  
              for ((i=0; i<=55; i++)); do 
                  msg_us="MSGUS$(printf "%02d" $i)"
                  [ "${!msg_us}" == "" ] && continue
                  msg_ot="MSG${lcode}$(printf "%02d" $i)"            
                  #echo "$msg_ot: ${!msg_ot}"            
                  echo "#: $msg_ot " >> lang/${L}/LC_MESSAGES/tcrp.po
                  echo "msgid \"${!msg_us}\"" >> lang/${L}/LC_MESSAGES/tcrp.po
                  echo "msgstr \"${!msg_ot}\"" >> lang/${L}/LC_MESSAGES/tcrp.po
                  echo "" >> lang/${L}/LC_MESSAGES/tcrp.po
              done
              cat lang/${L}/LC_MESSAGES/tcrp.po
          done
          echo "make po end"
          
          echo "Convert po2mo begin"
          DEST_PATH="${ROOT_PATH}/lang"
          echo "${DEST_PATH}"
          for P in $(ls ${DEST_PATH}/*/LC_MESSAGES/tcrp.po 2>/dev/null); do
            # Use msgfmt command to compile the .po file into a binary .mo file
            echo "msgfmt ${P} to ${P/.po/.mo}"
            msgfmt ${P} -o ${P/.po/.mo}
          done
          echo "Convert po2mo end"
          
          ls -lrt ${DEST_PATH}/*/LC_MESSAGES/
          tar -zcvf lang.tgz -C ${DEST_PATH} .          
      - name: Commit and push changes
        run: |
          git add .
          git commit -a -m "upload .po .mo"
          git push            
